version: '3'
services:
  react-app:
    image: react-app
    stdin_open: true
    ports:
      - 3000:3000
    networks:
      - wireframe-app

  api-server:
    image: api-server
    ports:
      - 8080:8080
    environment:
      - PORT=8080
      - DBURI=mongodb://mongo:27017/taskManagerDB
      - TESTINGDBURI='mongodb://mongo:27017/testing'
      - ENVIROMENT=development
    networks:
      - wireframe-app
    links:
      - mongo

  mongo:
    image: mongo:3.6.19-xenial
    ports:
      - 27017:27017
    networks:
      - wireframe-app

networks:
  wireframe-app:
    driver: bridge